version: "3.9"

services:
    server:
      container_name: prakticum-server-dev
      image: prakticum-server-dev
      build:
          context: .
          dockerfile: Dockerfile.server.dev
          args:
            SERVER_PORT: ${SERVER_PORT}
            VITE_HMR_PORT: ${VITE_HMR_PORT}
            VITE_SSR_HMR_PORT: ${VITE_SSR_HMR_PORT}
      command: /app/wait-for.sh postgres:${POSTGRES_PORT} -- yarn dev:docker
      restart: always
      depends_on:
        - postgres
      volumes:
        - ./packages/client:/app/packages/client
        - ./packages/server:/app/packages/server
      ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
        - "${VITE_HMR_PORT}:${VITE_HMR_PORT}"
        - "${VITE_SSR_HMR_PORT}:${VITE_SSR_HMR_PORT}"
      env_file: .env
      environment:
        NODE_ENV: development
        POSTGRES_HOST: postgres
      networks:
        - onebit

    postgres:
      container_name: prakticum-postgres
      image: postgres:14
      restart: always
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - onebit

    pgadmin:
      container_name: prakticum-pgadmin
      image: dpage/pgadmin4:6.20
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL: one.bit@dunge.on
        PGADMIN_DEFAULT_PASSWORD: mf-mod2
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      volumes:
        - ./tmp/pgadmin_data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - onebit

networks:
  onebit:
    driver: bridge
