version: "3.9"

services:
    postgres:
      container_name: prakticum-postgres
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
        - ./packages/server/db/sql/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
      networks:
        - onebit

    pgadmin:
      container_name: prakticum-pgadmin
      image: dpage/pgadmin4:6.20
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL: one.bit@dunge.on
        PGADMIN_DEFAULT_PASSWORD: mf-mod2
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      volumes:
        - ./tmp/pgadmin_data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - onebit

networks:
  onebit:
    driver: bridge
